version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    networks:
      - internal
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html/
      - ./docker/nginx:/etc/nginx/conf.d/
      - ./var/log/nginx:/var/log/nginx/

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    networks:
      - internal
    tty: true
    ports:
      - 9000:9000
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

networks:
  internal:
    driver: bridge